apiVersion: v1
kind: ReplicationController
metadata:
  name: my-service-with-replication-file-ver2
  labels:
    dc: Eng
    Team: TeamC
spec:
  replicas: 3
  selector:
    dc: Eng
    Team: TeamC
  template:
    metadata:
      name: my-cont-template-for-rc
      labels: 
        dc: Eng
        Team: TeamC
    spec:
      containers:
        - name: cont-by-svc-rc-file
          image: vimal13/apache-webserver-php
          resources: 
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-with-pod-srv-file-ver2
spec:
  type: NodePort
  selector:
    dc: Eng
    Team: TeamC
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31112


